"""add professionals

Revision ID: 39534903d22a
Revises: bbed347809dc
Create Date: 2026-08-06 21:21:48.718587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39534903d22a'
down_revision: Union[str, Sequence[str], None] = 'bbed347809dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('especialidade', sa.String(length=120), nullable=True),
    sa.Column('conselho', sa.String(length=30), nullable=True),
    sa.Column('conselho_uf', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profissionais_clinica_id'), 'profissionais', ['clinica_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profissionais_clinica_id'), table_name='profissionais')
    op.drop_table('profissionais')
    # ### end Alembic commands ###
