"""initial_schema

Revision ID: bbed347809dc
Revises: 
Create Date: 2026-08-06 19:26:50.878938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbed347809dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('plano', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.add_column(
        "pacientes",
        sa.Column("clinica_id", sa.Integer(), nullable=True),
    )

    connection = op.get_bind()

    clinica_inicial_id = connection.execute(
        sa.text(
            """
            INSERT INTO clinicas (nome, cnpj, telefone, email, plano, status)
            VALUES (
                'Clinica Inicial',
                '00000000000000',
                '0000000000',
                'admin@clinica.local',
                'starter',
                'ativo'
            )
            RETURNING id
            """
        )
    ).scalar_one()

    connection.execute(
        sa.text(
            """
            UPDATE pacientes
            SET clinica_id = :clinica_id
            WHERE clinica_id IS NULL
            """
        ),
        {"clinica_id": clinica_inicial_id},
    )

    op.alter_column(
        "pacientes",
        "clinica_id",
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.create_index(
        op.f("ix_pacientes_clinica_id"),
        "pacientes",
        ["clinica_id"],
        unique=False,
    )

    op.create_foreign_key(
        None,
        "pacientes",
        "clinicas",
        ["clinica_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.drop_index(op.f('ix_pacientes_clinica_id'), table_name='pacientes')
    op.drop_column('pacientes', 'clinica_id')
    op.drop_table('clinicas')
    # ### end Alembic commands ###
